name: kalasthali
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^6.3.2
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/category_grid/
